version: '3.8'

services:
  sightseeing_map:  
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"  
    volumes:
      - ./backend:/sightseeing-map
      - sightseeing_map_static_volume:/sightseeing-map/static
    env_file:
      - .env 
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - hubstation_frontend_network  

  nginx: 
    image: nginx:1.21-alpine
    ports:
      - "${NGINX_PORT}:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - sightseeing_map_static_volume:/sightseeing-map/static
    depends_on:
      - sightseeing_map
    networks:
      - hubstation_frontend_network  

volumes:
  sightseeing_map_static_volume: 
    driver: local

networks:
  hubstation_frontend_network:  
    external: true
