version: '3.8'

services:
  local_sightseeing_map_site:  
    labels:
      - test-project=true
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"  
    volumes:
      - ./backend:/sightseeing-map-site
      - sightseeing_map_static_volume:/sightseeing-map-site/static
    env_file:
      - .env 
    restart: unless-stopped
    networks:
      - hubstation_frontend_network  

  nginx: 
    labels:
      - test-project=true
    image: nginx:1.21-alpine
    ports:
      - "${NGINX_PORT}:80" 
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf  
    depends_on:
      - sightseeing_map_site  
    networks:
      - hubstation_frontend_network  

volumes:
  sightseeing_map_static_volume: 
    driver: local

networks:
  hubstation_frontend_network:  
    external: true
