
import './style/global.css';
import Header from "./component/Header";
import Footer from "./component/Footer";

import Head from "next/head";

export const metadata = {
  title: "SightseeingMap",
  description: "Generated by Next.js",
  openGraph: {
    title: "My Next.js App",
    description: "A modern web application built with Next.js",
    images: [
      {
        url: "/img/logo.png",
        width: 200,
        height: 150,
        alt: "local sightseeing Logo",
      },
    ],
    siteName: "My Next.js App",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />

        
      </Head>
      <body>
        <div id="wrapper">
        
          <Header />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}