import './App.css'
import Footer from './components/nav/Footer'
import Header from './components/nav/Header'
 
export const metadata = {
  title: 'Sightseeing Map',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Footer/>
    </html>
  )
}