name: Deploy Sightseeing Map App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Reminder to change the directory to the correct one
            cd ~/sightseeing_map_test

            # Pull latest changes
            git pull origin main

            # Make sure scripts are executable
            chmod +x ./scripts/*.sh

            # Initialize the environment
            ./scripts/initialize_environment.sh

            # Collect static files
            ./scripts/collect_static.sh
